### ISSUE TITLE
stopScan() does requires Bluetooth ON

### ISSUE THREAD

**Issue by GregoryIwanek** [NordicSemiconductor/Android-DFU-Library#198] opened 2019-08-06 13:07 UTC
Hello.
Method `BluetoothLeScannerCompat.getScanner().stopScan(scanCallback)` triggers private method `void stopScanInternal(@NonNull final ScanCallback callback)` which as one of steps checks if Bluetooth is turned ON.
Scan should be lengthy process of at least few seconds to make sure it finds advertising devices.
Problem is, during that time user can turn OFF Bluetooth on the device. 
To my surprise, after turning off bluetooth during scan process, we end up with a crash ( from `BluetoothLeUtils.checkAdapterStateOn(adapter)`) when called `stopScan(scanCallback)`.
Option to skip this crash is to allow `stopScan(scanCallback)` only if Bluetooth is in state ON, but as a result we have infinite-loop scanning which will stress device/battery with redundant operations. Shouldn't scanning service stop immediately with results/failure when Bluetooth is turned OFF? 

I had a look on demo project, but it's same implementation with delayed 5000ms handler to trigger scan stop.

Was it intentional behaviour? In my opinion it's a bug very possible for the users to trigger.
I looked through issues page and haven't seen this mentioned. Is there any obvious solution which I might missing? Sorry in advance if there is, I just started to use this lib.

**Comment by philips77** [comment] 2020-02-12 08:33
I believe the issue is for [Android Scanner Compat Library](https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library), not DFU Library.
It has been fixed by this commit: https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library/commit/8a20607d22f78e57700bf0b1fe911287d571c0ef

**Closed by philips77** 2020-02-12 08:33 UTC
