### ISSUE TITLE
Program type already present: no.nordicsemi.android.dfu.BaseButtonlessDfuImpl$ButtonlessBluetoothCallback

### ISSUE THREAD

**Issue by Basavaraj1991** [NordicSemiconductor/Android-DFU-Library#119] opened 2018-07-24 05:55 UTC
Hi

I'm getting the below issue while generating the signed apk with debug and release.

Program type already present: no.nordicsemi.android.dfu.BaseButtonlessDfuImpl$ButtonlessBluetoothCallback

**Comment by philips77** [comment] 2018-07-24 06:03
Duplicate of #118

**Closed by philips77** 2018-07-24 06:03 UTC
