### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to get length of null array

### ISSUE THREAD

**Issue by alixwar** [NordicSemiconductor/Android-DFU-Library#143] opened 2018-10-25 13:37 UTC
A crash was reported in our app that bundles version 1.7.0 of the DFU library. Details below:

Device
Brand: samsung
Model: SM-G950F
Orientation: Portrait
RAM free: 1.28 GB
Disk free: 47.78 GB

Operating System
Version: 8.0.0
Orientation: Portrait
Rooted: No

```
no.nordicsemi.android.dfu.internal.ArchiveInputStream.read (ArchiveInputStream.java:338)
no.nordicsemi.android.dfu.SecureDfuImpl.sendFirmware (SecureDfuImpl.java:461)
no.nordicsemi.android.dfu.SecureDfuImpl.performDfu (SecureDfuImpl.java:221)
no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent (DfuBaseService.java:1186)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:68)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.os.HandlerThread.run (HandlerThread.java:65)
```

**Comment by philips77** [comment] 2018-10-25 13:42
Duplicate of #97. It has been fixed by #126 and will be released in 1.8.0.

**Comment by philips77** [comment] 2018-10-29 12:15
Released.

**Comment by LoPoBo** [comment] 2018-10-29 13:30
The stacktrace of 1.8.0:

    java.lang.NullPointerException: Attempt to get length of null array
        at no.nordicsemi.android.dfu.internal.ArchiveInputStream.read(ArchiveInputStream.java:338)
        at no.nordicsemi.android.dfu.SecureDfuImpl.sendFirmware(SecureDfuImpl.java:499)
        at no.nordicsemi.android.dfu.SecureDfuImpl.performDfu(SecureDfuImpl.java:257)
        at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1236)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by philips77** [comment] 2018-10-29 13:38
Could you paste some LogCat logs from before the crash occurs?

**Comment by LoPoBo** [comment] 2018-10-29 13:58
Sure. Here it is:

    10-29 14:20:26.299 2380-2380/my.app I/DfuBaseService: DFU service created. Version: 1.8.0
    10-29 14:20:26.408 2380-2380/my.app I/DfuService: [DFU] Firmware file opened successfully
    10-29 14:20:26.410 2380-2531/my.app I/DfuBaseService: Connecting to the device...
    10-29 14:20:26.767 2380-2380/my.app I/DfuBaseService: Action received: android.bluetooth.device.action.ACL_CONNECTED
    10-29 14:20:26.773 2380-2393/my.app I/DfuBaseService: Connected to GATT server
    10-29 14:20:26.777 2380-2380/my.app I/DfuService: [DFU] Connected to F1:77:EB:BC:F8:48
    10-29 14:20:26.788 2380-2393/my.app I/DfuBaseService: Attempting to start service discovery... succeed
    10-29 14:20:27.784 2380-2393/my.app I/DfuBaseService: Services discovered
    10-29 14:20:27.789 2380-2380/my.app I/DfuService: [DFU] Services discovered
    10-29 14:20:27.793 2380-2531/my.app W/DfuImpl: Secure DFU bootloader found
    10-29 14:20:28.814 2380-2531/my.app I/DfuImpl: Requesting MTU = 517
    10-29 14:20:28.859 2380-2393/my.app I/DfuImpl: MTU changed to: 23
    10-29 14:20:28.860 2380-2531/my.app I/DfuImpl: Enabling notifications...
    10-29 14:20:28.861 2380-2380/my.app I/DfuService: [DFU] MTU changed to: 23
    10-29 14:20:28.916 2380-2380/my.app I/DfuService: [DFU] Data written to descr.8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 01-00
    10-29 14:20:28.919 2380-2380/my.app I/DfuService: [DFU] Notifications enabled
    10-29 14:20:29.918 2380-2531/my.app I/DfuImpl: Setting object to Command (Op Code = 6, Type = 1)
    10-29 14:20:29.966 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 06-01
    10-29 14:20:29.967 2380-2531/my.app I/DfuImpl: Command object info received (Max size = 256, Offset = 0, CRC = 00000000)
    10-29 14:20:29.967 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-06-01-00-01-00-00-00-00-00-00-00-00-00-00
    10-29 14:20:29.969 2380-2531/my.app I/DfuImpl: Sending the number of packets before notifications (Op Code = 2, Value = 0)
    10-29 14:20:29.969 2380-2380/my.app I/DfuService: [DFU] Command object info received (Max size = 256, Offset = 0, CRC = 00000000)
    10-29 14:20:30.004 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-02-01
    10-29 14:20:30.005 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-02-01
    10-29 14:20:30.009 2380-2531/my.app I/DfuImpl: Creating Init packet object (Op Code = 1, Type = 1, Size = 136)
    10-29 14:20:30.010 2380-2380/my.app I/DfuService: [DFU] Packet Receipt Notif disabled (Op Code = 2, Value = 0)
    10-29 14:20:30.059 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-01-01
    10-29 14:20:30.060 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-01-01
    10-29 14:20:30.068 2380-2531/my.app I/DfuImpl: Sending 136 bytes of init packet...
        Sending init packet (Value = 12-85-01-0A-3F-08-01-12-3B-08-8A-0A-10-34-1A-02-98-01-20-00)
    10-29 14:20:30.068 2380-2380/my.app I/DfuService: [DFU] Command object created
    10-29 14:20:30.078 2380-2531/my.app I/DfuImpl: Sending init packet (Value = 28-00-30-00-38-E4-D3-0B-42-24-08-03-12-20-CF-08-18-D6-8A-DF)
    10-29 14:20:30.079 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): 12-85-01-0A-3F-08-01-12-3B-08-8A-0A-10-34-1A-02-98-01-20-00
    10-29 14:20:30.084 2380-2531/my.app I/DfuImpl: Sending init packet (Value = 6B-C7-8E-1F-6E-58-9F-76-21-41-09-56-63-CE-6A-4E-35-FF-11-95)
    10-29 14:20:30.084 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): 28-00-30-00-38-E4-D3-0B-42-24-08-03-12-20-CF-08-18-D6-8A-DF
    10-29 14:20:30.090 2380-2531/my.app I/DfuImpl: Sending init packet (Value = AE-3E-12-95-DA-82-48-00-10-00-1A-40-2A-C3-91-F9-1D-03-AC-84)
    10-29 14:20:30.091 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): 6B-C7-8E-1F-6E-58-9F-76-21-41-09-56-63-CE-6A-4E-35-FF-11-95
    10-29 14:20:30.101 2380-2531/my.app I/DfuImpl: Sending init packet (Value = 8A-2F-9E-79-B4-6B-9C-84-BE-61-70-D8-AF-6B-C7-FE-7B-35-BE-2F)
    10-29 14:20:30.102 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): AE-3E-12-95-DA-82-48-00-10-00-1A-40-2A-C3-91-F9-1D-03-AC-84
    10-29 14:20:30.109 2380-2531/my.app I/DfuImpl: Sending init packet (Value = 02-FC-0B-9E-D6-58-1E-62-46-26-B1-7C-2C-FD-11-CF-EF-66-75-71)
    10-29 14:20:30.115 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): 8A-2F-9E-79-B4-6B-9C-84-BE-61-70-D8-AF-6B-C7-FE-7B-35-BE-2F
    10-29 14:20:30.123 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): 02-FC-0B-9E-D6-58-1E-62-46-26-B1-7C-2C-FD-11-CF-EF-66-75-71
    10-29 14:20:30.129 2380-2531/my.app I/DfuImpl: Sending init packet (Value = 21-5A-6C-CA-2A-2C-DE-B6-C4-52-01-E7-80-CC-7F-37)
    10-29 14:20:30.136 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90002-f315-4f60-9fb8-838830daea50, value (0x): 21-5A-6C-CA-2A-2C-DE-B6-C4-52-01-E7-80-CC-7F-37
    10-29 14:20:30.136 2380-2531/my.app I/DfuImpl: Sending Calculate Checksum command (Op Code = 3)
    10-29 14:20:30.136 2380-2380/my.app I/DfuService: [DFU] Command object sent (CRC = 6A6C2E75)
    10-29 14:20:30.172 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 03
    10-29 14:20:30.174 2380-2531/my.app I/DfuImpl: Checksum received (Offset = 136, CRC = 6A6C2E75)
        Executing init packet (Op Code = 4)
    10-29 14:20:30.175 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-03-01-88-00-00-00-75-2E-6C-6A
        [DFU] Checksum received (Offset = 136, CRC = 6A6C2E75)
    10-29 14:20:30.209 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 04
    10-29 14:20:30.341 2380-2531/my.app I/DfuImpl: Setting object to Data (Op Code = 6, Type = 2)
    10-29 14:20:30.343 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-04-01
        [DFU] Command object executed
    10-29 14:20:30.379 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-06-01-00-10-00-00-00-00-00-00-00-00-00-00
    10-29 14:20:30.380 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-06-01-00-10-00-00-00-00-00-00-00-00-00-00
    10-29 14:20:30.380 2380-2531/my.app I/DfuImpl: Data object info received (Max size = 4096, Offset = 0, CRC = 00000000)
    10-29 14:20:30.383 2380-2380/my.app I/DfuService: [DFU] Data object info received (Max size = 4096, Offset = 0, CRC = 00000000)
    10-29 14:20:30.412 2380-2531/my.app I/DfuImpl: Creating Data object (Op Code = 1, Type = 2, Size = 4096) (1/47)
    10-29 14:20:30.510 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-01-01
    10-29 14:20:30.511 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-01-01
    10-29 14:20:30.512 2380-2531/my.app I/DfuImpl: Uploading firmware...
    10-29 14:20:30.515 2380-2380/my.app I/DfuService: [DFU] Data object (1/47) created
    10-29 14:20:30.516 2380-2380/my.app I/DfuService: [DFU] Uploading firmware...
    10-29 14:20:31.228 2380-2531/my.app I/DfuImpl: Sending Calculate Checksum command (Op Code = 3)
    10-29 14:20:32.218 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 03
    10-29 14:20:32.236 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-03-01-00-10-00-00-A9-9B-C8-5A
    10-29 14:20:32.236 2380-2531/my.app I/DfuImpl: Checksum received (Offset = 4096, CRC = 5AC89BA9)
    10-29 14:20:32.237 2380-2531/my.app I/DfuImpl: Executing data object (Op Code = 4)
    10-29 14:20:32.237 2380-2380/my.app I/DfuService: [DFU] Checksum received (Offset = 4096, CRC = 5AC89BA9)
    10-29 14:20:32.291 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-04-01
        [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-04-01
    10-29 14:20:32.293 2380-2531/my.app I/DfuImpl: Creating Data object (Op Code = 1, Type = 2, Size = 4096) (2/47)
    10-29 14:20:32.293 2380-2380/my.app I/DfuService: [DFU] Data object executed
    10-29 14:20:32.422 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-01-01
    10-29 14:20:32.423 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-01-01

...

    10-29 14:21:28.205 2380-2531/my.app I/DfuImpl: Uploading firmware...
    10-29 14:21:28.205 2380-2380/my.app I/DfuService: [DFU] Data object (32/47) created
    10-29 14:21:28.206 2380-2380/my.app I/DfuService: [DFU] Uploading firmware...
    10-29 14:21:29.078 2380-2531/my.app I/DfuImpl: Sending Calculate Checksum command (Op Code = 3)
    10-29 14:21:33.776 2380-2490/my.app E/DfuImpl: Characteristic write error: 133
    10-29 14:21:33.779 2380-2380/my.app E/DfuService: [DFU] Error (0x85): GATT ERROR
    10-29 14:21:33.781 2380-2490/my.app W/DfuBaseService: Target device disconnected with status: 8
    10-29 14:21:33.782 2380-2531/my.app E/DfuBaseService: Unable to write Op Code 3 (error 133)
    10-29 14:21:33.792 2380-2531/my.app I/DfuBaseService: Refreshing result: true
        Cleaning up...
    10-29 14:21:33.794 2380-2380/my.app I/DfuBaseService: Action received: android.bluetooth.device.action.ACL_DISCONNECTED
    10-29 14:21:34.435 2380-2380/my.app E/DfuProgressListener: onError(deviceAddress=F1:77:EB:BC:F8:48, error=133, errorType=2, message=GATT ERROR)
    10-29 14:21:34.436 2380-2380/my.app W/DfuDialogFragment: Error occurred. Retrying...
    10-29 14:21:34.483 2380-2380/my.app I/DfuService: [DFU] Firmware file opened successfully
    10-29 14:21:36.508 2380-2531/my.app I/DfuBaseService: Connecting to the device...
    10-29 14:21:36.802 2380-2380/my.app I/DfuBaseService: Action received: android.bluetooth.device.action.ACL_CONNECTED
    10-29 14:21:36.805 2380-2490/my.app I/DfuBaseService: Connected to GATT server
    10-29 14:21:36.806 2380-2380/my.app I/DfuService: [DFU] Connected to F1:77:EB:BC:F8:48
    10-29 14:21:36.814 2380-2490/my.app I/DfuBaseService: Attempting to start service discovery... succeed
    10-29 14:21:37.707 2380-2490/my.app I/DfuBaseService: Services discovered
    10-29 14:21:37.709 2380-2380/my.app I/DfuService: [DFU] Services discovered
    10-29 14:21:37.716 2380-2531/my.app W/DfuImpl: Secure DFU bootloader found
    10-29 14:21:38.734 2380-2531/my.app I/DfuImpl: Requesting MTU = 517
    10-29 14:21:38.768 2380-2490/my.app I/DfuImpl: MTU changed to: 23
    10-29 14:21:38.769 2380-2380/my.app I/DfuService: [DFU] MTU changed to: 23
    10-29 14:21:38.769 2380-2531/my.app I/DfuImpl: Enabling notifications...
    10-29 14:21:38.824 2380-2380/my.app I/DfuService: [DFU] Data written to descr.8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 01-00
    10-29 14:21:38.826 2380-2380/my.app I/DfuService: [DFU] Notifications enabled
    10-29 14:21:39.825 2380-2531/my.app I/DfuImpl: Setting object to Command (Op Code = 6, Type = 1)
    10-29 14:21:39.876 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 06-01
    10-29 14:21:39.878 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-06-01-00-01-00-00-88-00-00-00-75-2E-6C-6A
    10-29 14:21:39.879 2380-2531/my.app I/DfuImpl: Command object info received (Max size = 256, Offset = 136, CRC = 6A6C2E75)
    10-29 14:21:39.880 2380-2531/my.app I/DfuImpl: Init packet CRC is the same
        -> Whole Init packet was sent before
    10-29 14:21:39.881 2380-2531/my.app I/DfuImpl: Executing init packet (Op Code = 4)
    10-29 14:21:39.890 2380-2380/my.app I/DfuService: [DFU] Command object info received (Max size = 256, Offset = 136, CRC = 6A6C2E75)
    10-29 14:21:39.891 2380-2380/my.app I/DfuService: [DFU] Received CRC match Init packet
    10-29 14:21:39.931 2380-2531/my.app I/DfuImpl: Setting object to Data (Op Code = 6, Type = 2)
    10-29 14:21:39.932 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-04-01
    10-29 14:21:39.933 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-04-01
    10-29 14:21:39.934 2380-2380/my.app I/DfuService: [DFU] Command object executed
    10-29 14:21:39.969 2380-2380/my.app I/DfuService: [DFU] Notification received from 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-06-01-00-10-00-00-00-F0-01-00-17-53-6A-6C
    10-29 14:21:39.970 2380-2380/my.app I/DfuService: [DFU] Data written to 8ec90001-f315-4f60-9fb8-838830daea50, value (0x): 60-06-01-00-10-00-00-00-F0-01-00-17-53-6A-6C
    10-29 14:21:39.971 2380-2531/my.app I/DfuImpl: Data object info received (Max size = 4096, Offset = 126976, CRC = 6C6A5317)
    10-29 14:21:39.972 2380-2380/my.app I/DfuService: [DFU] Data object info received (Max size = 4096, Offset = 126976, CRC = 6C6A5317)
    10-29 14:21:39.980 2380-2531/my.app E/AndroidRuntime: FATAL EXCEPTION: IntentService[DfuBaseService]
        Process: my.app, PID: 2380
        java.lang.NullPointerException: Attempt to get length of null array
            at no.nordicsemi.android.dfu.internal.ArchiveInputStream.read(ArchiveInputStream.java:338)
            at no.nordicsemi.android.dfu.SecureDfuImpl.sendFirmware(SecureDfuImpl.java:499)
            at no.nordicsemi.android.dfu.SecureDfuImpl.performDfu(SecureDfuImpl.java:257)
            at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1236)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
            at android.os.Handler.dispatchMessage(Handler.java:105)
            at android.os.Looper.loop(Looper.java:164)
            at android.os.HandlerThread.run(HandlerThread.java:65)
    10-29 14:21:45.040 2380-2419/my.app I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    10-29 14:21:45.041 2380-2419/my.app I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    10-29 14:22:40.478 2380-2380/my.app I/DfuBaseService: DFU service destroyed

**Comment by LoPoBo** [comment] 2018-10-30 07:28
I will investigate it

**Comment by LoPoBo** [comment] 2018-11-05 13:54
The problem is that when `SecureDfuImpl.sendFirmware(BluetoothGatt)` tries to resume it tries to read all the executed bytes (L495) from the stream but since the stream is reused (and not reset to the beginning of the file) it instead reads the rest of the file (and thus setting `currentSource` to `null`). On the next read (L499) the NPE occurs.

I'm not sure there is a simple solution to this.

There also seem to be some confusion/mismatch in how the `mark`/`reset` methods are used in the code. In some places it seems like it is assumed that `reset` resets the stream to the beginning.

**Comment by LoPoBo** [comment] 2018-11-05 13:54
In several places in `SecureDfuImpl` the field `mFirmwareStream` is cast to `ArchiveInputStream` with no apparent type check. Can it be assumed that the `mFirmwareStream` is always an instance of `ArchiveInputStream` in `SecureDfuImpl`? If so, I could add a "full reset" method in `ArchiveInputStream` which could be called before the read on L495.

**Comment by philips77** [comment] 2018-12-04 09:22
Hello @LoPoBo,
Sorry for the very long delay. 
First of all, indeed the Secure DFU Impl assumes that the ZIP file and `AchiveInputStream` are used. Other methods are deprecated and I don't think I'll change that, as it's much easier just to create the ZIP file then modify the Secure DFU Impl to accept *bin* and *dat* files separately. But thank you for pointing that out. This should be documented.
Secondly, restarting the service is problematic. As you've noticed, the service `resets()` the stream before uploading, but as it is reusing the same `InputStream` object (in that case `ArchiveInputStream`), and in the previous upload it put some marks there, the reset won't do "full reset". I'll try to fix it now.

**Comment by philips77** [comment] 2018-12-04 09:36
@LoPoBo, the commit added `fullReset()` method in the `ArchiveInputStream`. It is called every time the DFU is started. This resets the byte counter to 0 for the current stream, so if the disconnection happened during App update, after SD+BL were already updated, the App stream will be reset to 0, not the SB+BL. However, I couldn't test it properly, so I'll wait with publishing until you test it. Thank you!

**Closed** 2019-01-29 14:21 UTC
Labels: bug

**Comment by LoPoBo** [comment] 2019-02-04 14:48
Hi again. Unfortunately I had changed project and thus were unable to test your fix. Sorry for not replying earlier!
