### ISSUE TITLE
Attempt to invoke virtual method 'void no.nordicsemi.android.dfu.DfuBaseService.sendLogBroadcast(int, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by Yongle-Fu** [NordicSemiconductor/Android-DFU-Library#322] opened 2022-02-14 04:11 UTC
```
W/BluetoothGatt(31289): java.lang.NullPointerException: Attempt to invoke virtual method 'void no.nordicsemi.android.dfu.DfuBaseService.sendLogBroadcast(int, java.lang.String)' on a null object reference
W/BluetoothGatt(31289): 	at no.nordicsemi.android.dfu.BaseDfuImpl$BaseBluetoothGattCallback.onPhyUpdate(BaseDfuImpl.java:207)
W/BluetoothGatt(31289): 	at no.nordicsemi.android.dfu.DfuBaseService$5.onPhyUpdate(DfuBaseService.java:1009)
W/BluetoothGatt(31289): 	at android.bluetooth.BluetoothGatt$1$2.run(BluetoothGatt.java:228)
W/BluetoothGatt(31289): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:823)
W/BluetoothGatt(31289): 	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:47)
W/BluetoothGatt(31289): 	at android.bluetooth.BluetoothGatt$1.onPhyUpdate(BluetoothGatt.java:223)
W/BluetoothGatt(31289): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:215)
W/BluetoothGatt(31289): 	at android.os.Binder.execTransactInternal(Binder.java:1184)
W/BluetoothGatt(31289): 	at android.os.Binder.execTransact(Binder.java:1143)
D/BluetoothGatt(31289): onSearchComplete() = Device=58:94:B2:00:02:3A Status=0
```
no.nordicsemi.android:dfu V1.12.0

**Comment by philips77** [comment] 2023-05-22 13:22
Duplicate of #215

**Closed** 2023-05-31 11:35 UTC
Labels: bug
